version: '3.7'
services:
  pg-destination:
    restart: always
    container_name: pg-destination
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=destination
    ports:
      - "5105:5432"
    volumes:
      - ./createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
      - ./docker/volumes/postgres2:/var/lib/postgresql/data:delegated
  pg-source:
    restart: always
    container_name: pg-source
    image: postgres
    shm_size: 1gb
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=source
    ports:
      - "5205:5432"
    volumes:
      - ./createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
      - ./docker/volumes/postgres3:/var/lib/postgresql/data:delegated